<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <RootNamespace>TenantFlow.Api</RootNamespace>
	  <AssemblyName>TenantFlow.Api</AssemblyName>
  </PropertyGroup>

	<ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>    
    <PackageReference Include="Scalar.AspNetCore" Version="2.3.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TenantFlow.Application\TenantFlow.Application.csproj" />
    <ProjectReference Include="..\TenantFlow.Infrastructure\TenantFlow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
